<?php
// Commenting out a castle's entry will remove it from the castles page
// and exclude it from being a factor in the guild ranking.
return array(
	// iRO Names
	 0 => 'Нойшванштайн',
	 1 => 'Хоэншвангау',
	 2 => 'Нюрнберг',
	 3 => 'Вюрцбург',
	 4 => 'Ротенбург-об-дер-Таубер',
	 5 => 'Рефрион',
	 6 => 'Юльбриго',
	 7 => 'Иснельф',
	 8 => 'Бергель',
	 9 => 'Мельсдеч',
	10 => 'Яркий Арбор',
	11 => 'Алый дом',
	12 => 'Святая тень',
	13 => 'Священный алтарь',
	14 => 'Бамбуковый лес',
	15 => 'Кримхилд',
	16 => 'Сбанхилт',
	17 => 'Фадридх',
	18 => 'Скогул',
	19 => 'Гондул',
	20 => 'Чайный домик',
	21 => 'Минка',
	22 => 'Нагая',
	23 => 'Матия',
	24 => 'Химин',
	25 => 'Андлеран',
	26 => 'Бидлинд',
	27 => 'Гэлид',
	28 => 'Скидбладнир',
	29 => 'Мардол',
	30 => 'Тюр',
	31 => 'Хорн',
	32 => 'Гефн',
	33 => 'Бандис'
	// kRO Names
	/**
	 * 0 => 'Noisyubantian',
	 * 1 => 'Hohensyubangawoo',
	 * 2 => 'Nyirenverk',
	 * 3 => 'Byirtsburi',
	 * 4 => 'Rotenburk',
	 * 5 => 'Reprion',
	 * 6 => 'Yolbriger',
	 * 7 => 'Isinlife',
	 * 8 => 'Berigel',
	 * 9 => 'Melsedetsu',
	 *10 => 'Mingting',
	 *11 => 'Tiantan',
	 *12 => 'Fuying',
	 *13 => 'Honglou',
	 *14 => 'Zhulinxian',
	 *15 => 'Creamhilt',
	 *16 => 'Sbanhealt',
	 *17 => 'Lazrigees',
	 *18 => 'Squagul',
	 *19 => 'Guindull',
	 *20 => 'Novice Aldebaran',
	 *21 => 'Novice Geffen',
	 *22 => 'Novice Payon',
	 *23 => 'Novice Prontera',
	 *24 => 'Himinn',
	 *25 => 'Andlangr',
	 *26 => 'Viblainn',
	 *27 => 'Hljod',
	 *28 => 'Skidbladnir',
	 *29 => 'Mardol',
	 *30 => 'Cyr',
	 *31 => 'Horn',
	 *32 => 'Gefn',
	 *33 => 'Bandis'
	 */
)
?>
